{"name": "test_login_negative", "status": "broken", "statusDetails": {"message": "TypeError: 'WebDriver' object is not callable", "trace": "Setup = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"161c7ed9a880fa12d0c7a69e27c1ba59\")>\n\n    def test_login_negative(Setup):\n>       driver = Setup()\nE       TypeError: 'WebDriver' object is not callable\n\ntest_vwo_login.py:21: TypeError"}, "start": 1728028592161, "stop": 1728028592162, "uuid": "60697b35-aaa3-473a-9e61-3b6ab8b59c67", "historyId": "8be6628af41c999eb267bfd17245a1df", "testCaseId": "8be6628af41c999eb267bfd17245a1df", "fullName": "tests.vwoLoginTests.test_vwo_login#test_login_negative", "labels": [{"name": "parentSuite", "value": "tests.vwoLoginTests"}, {"name": "suite", "value": "test_vwo_login"}, {"name": "host", "value": "DESKTOP-O5T1HPJ"}, {"name": "thread", "value": "16012-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.vwoLoginTests.test_vwo_login"}]}